#!/bin/sh
set -e

. /usr/share/debconf/confmodule         

db_version 2.0
db_title "Obiwan Setup" 
db_capb backup

INTF=$(ip link | grep BROADCAST | awk '{split($2,a,"@"); print a[1]}' | sed s/://g | tr '\n' ',' | sed 's/,/,\ /g' | awk '{print substr($0,0,length()-1)}')
db_subst obiwan/intfSelect interfaces $INTF

STATE=1
while [ true ]; do
	case $STATE in
	1)
		db_input high obiwan/mysqlRootPassword || true
	;;
	2)
		db_input high obiwan/intfSelect || true
	;;
	3)
		db_input high obiwan/intfModeSelect || true
	;;
	4)
		db_beginblock
		db_input high obiwan/intfStaticAddress || true
		db_input high obiwan/intfStaticNetmask || true
		db_input high obiwan/intfStaticGateway || true
		
		db_endblock
	;;
	*)
		break;
	;;
	
	esac
	
	if db_go; then
		
		if [ $STATE -eq 3 ]; then
			db_get obiwan/intfModeSelect
			
			[ "$RET" = "DHCP" ] && STATE=$(($STATE + 1))
		fi
		
		STATE=$(($STATE + 1))
	else
		STATE=$(($STATE - 1))
	fi
done

if [ $STATE -eq 0 ]; then
	exit 10
fi


