#!/bin/sh

set -e
. /usr/share/debconf/confmodule

# stop any services
service pppoe stop || true

# tidy up FreeRADIUS
if [ -e /etc/freeradius/sites-enabled/obiwan ]
then
	rm -f /etc/freeradius/sites-enabled/obiwan || true
fi

# add back the old default config
if [ ! -e /etc/freeradius/sites-enabled/default ]
then
	ln -s /etc/freeradius/sites-available/default /etc/freeradius/sites-enabled/default || true
fi


mv -f /etc/freeradius/sql.conf.bak /etc/freeradius/sql.conf || true
mv -f /etc/freeradius/sqlippool.conf.bak /etc/freeradius/sqlippool.conf || true

if [ -e /etc/network/interfaces.bak ]
then
	rm /etc/network/interfaces || true
	mv /etc/network/interfaces.bak /etc/network/interfaces || true
fi

rm -f /etc/init/firewall.conf || true
rm -f /etc/init/pppoe.conf || true
rm -f /etc/init/rasconfig.conf || true

# restart services
service networking restart || true
service freeradius restart || true

# end the script
db_purge
db_stop
